# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from whoop_client.models.recovery_score import RecoveryScore

class TestRecoveryScore(unittest.TestCase):
    """RecoveryScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecoveryScore:
        """Test RecoveryScore
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecoveryScore`
        """
        model = RecoveryScore()
        if include_optional:
            return RecoveryScore(
                user_calibrating = False,
                recovery_score = 44.0,
                resting_heart_rate = 64.0,
                hrv_rmssd_milli = 31.813562,
                spo2_percentage = 95.6875,
                skin_temp_celsius = 33.7
            )
        else:
            return RecoveryScore(
                user_calibrating = False,
                recovery_score = 44.0,
                resting_heart_rate = 64.0,
                hrv_rmssd_milli = 31.813562,
        )
        """

    def testRecoveryScore(self):
        """Test RecoveryScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
