# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whoop_client.api.workout_api import WorkoutApi


class TestWorkoutApi(unittest.TestCase):
    """WorkoutApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkoutApi()

    def tearDown(self) -> None:
        pass

    def test_get_workout_by_id(self) -> None:
        """Test case for get_workout_by_id

        """
        pass

    def test_get_workout_collection(self) -> None:
        """Test case for get_workout_collection

        """
        pass


if __name__ == '__main__':
    unittest.main()
