# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from whoop_client.models.sleep_stage_summary import SleepStageSummary

class TestSleepStageSummary(unittest.TestCase):
    """SleepStageSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SleepStageSummary:
        """Test SleepStageSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SleepStageSummary`
        """
        model = SleepStageSummary()
        if include_optional:
            return SleepStageSummary(
                total_in_bed_time_milli = 30272735,
                total_awake_time_milli = 1403507,
                total_no_data_time_milli = 0,
                total_light_sleep_time_milli = 14905851,
                total_slow_wave_sleep_time_milli = 6630370,
                total_rem_sleep_time_milli = 5879573,
                sleep_cycle_count = 3,
                disturbance_count = 12
            )
        else:
            return SleepStageSummary(
                total_in_bed_time_milli = 30272735,
                total_awake_time_milli = 1403507,
                total_no_data_time_milli = 0,
                total_light_sleep_time_milli = 14905851,
                total_slow_wave_sleep_time_milli = 6630370,
                total_rem_sleep_time_milli = 5879573,
                sleep_cycle_count = 3,
                disturbance_count = 12,
        )
        """

    def testSleepStageSummary(self):
        """Test SleepStageSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
