# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from whoop_client.models.user_body_measurement import UserBodyMeasurement

class TestUserBodyMeasurement(unittest.TestCase):
    """UserBodyMeasurement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserBodyMeasurement:
        """Test UserBodyMeasurement
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserBodyMeasurement`
        """
        model = UserBodyMeasurement()
        if include_optional:
            return UserBodyMeasurement(
                height_meter = 1.8288,
                weight_kilogram = 90.7185,
                max_heart_rate = 200
            )
        else:
            return UserBodyMeasurement(
                height_meter = 1.8288,
                weight_kilogram = 90.7185,
                max_heart_rate = 200,
        )
        """

    def testUserBodyMeasurement(self):
        """Test UserBodyMeasurement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
