# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from whoop_client.models.paginated_recovery_response import PaginatedRecoveryResponse

class TestPaginatedRecoveryResponse(unittest.TestCase):
    """PaginatedRecoveryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedRecoveryResponse:
        """Test PaginatedRecoveryResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedRecoveryResponse`
        """
        model = PaginatedRecoveryResponse()
        if include_optional:
            return PaginatedRecoveryResponse(
                records = [
                    whoop_client.models.recovery.Recovery(
                        cycle_id = 93845, 
                        sleep_id = 10235, 
                        user_id = 10129, 
                        created_at = '2022-04-24T11:25:44.774Z', 
                        updated_at = '2022-04-24T14:25:44.774Z', 
                        score_state = 'SCORED', 
                        score = whoop_client.models.recovery_score.RecoveryScore(
                            user_calibrating = False, 
                            recovery_score = 44.0, 
                            resting_heart_rate = 64.0, 
                            hrv_rmssd_milli = 31.813562, 
                            spo2_percentage = 95.6875, 
                            skin_temp_celsius = 33.7, ), )
                    ],
                next_token = 'MTIzOjEyMzEyMw'
            )
        else:
            return PaginatedRecoveryResponse(
        )
        """

    def testPaginatedRecoveryResponse(self):
        """Test PaginatedRecoveryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
