# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from whoop_client.models.paginated_cycle_response import PaginatedCycleResponse

class TestPaginatedCycleResponse(unittest.TestCase):
    """PaginatedCycleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedCycleResponse:
        """Test PaginatedCycleResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedCycleResponse`
        """
        model = PaginatedCycleResponse()
        if include_optional:
            return PaginatedCycleResponse(
                records = [
                    whoop_client.models.cycle.Cycle(
                        id = 93845, 
                        user_id = 10129, 
                        created_at = '2022-04-24T11:25:44.774Z', 
                        updated_at = '2022-04-24T14:25:44.774Z', 
                        start = '2022-04-24T02:25:44.774Z', 
                        end = '2022-04-24T10:25:44.774Z', 
                        timezone_offset = '-05:00', 
                        score_state = 'SCORED', 
                        score = whoop_client.models.cycle_score.CycleScore(
                            strain = 5.2951527, 
                            kilojoule = 8288.297, 
                            average_heart_rate = 68, 
                            max_heart_rate = 141, ), )
                    ],
                next_token = 'MTIzOjEyMzEyMw'
            )
        else:
            return PaginatedCycleResponse(
        )
        """

    def testPaginatedCycleResponse(self):
        """Test PaginatedCycleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
