# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whoop_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_get_body_measurement(self) -> None:
        """Test case for get_body_measurement

        """
        pass

    def test_get_profile_basic(self) -> None:
        """Test case for get_profile_basic

        """
        pass

    def test_revoke_user_o_auth_access(self) -> None:
        """Test case for revoke_user_o_auth_access

        """
        pass


if __name__ == '__main__':
    unittest.main()
