# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from whoop_client.models.sleep_needed import SleepNeeded

class TestSleepNeeded(unittest.TestCase):
    """SleepNeeded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SleepNeeded:
        """Test SleepNeeded
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SleepNeeded`
        """
        model = SleepNeeded()
        if include_optional:
            return SleepNeeded(
                baseline_milli = 27395716,
                need_from_sleep_debt_milli = 352230,
                need_from_recent_strain_milli = 208595,
                need_from_recent_nap_milli = -12312
            )
        else:
            return SleepNeeded(
                baseline_milli = 27395716,
                need_from_sleep_debt_milli = 352230,
                need_from_recent_strain_milli = 208595,
                need_from_recent_nap_milli = -12312,
        )
        """

    def testSleepNeeded(self):
        """Test SleepNeeded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
