# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from whoop_client.api.recovery_api import RecoveryApi


class TestRecoveryApi(unittest.TestCase):
    """RecoveryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecoveryApi()

    def tearDown(self) -> None:
        pass

    def test_get_recovery_collection(self) -> None:
        """Test case for get_recovery_collection

        """
        pass

    def test_get_recovery_for_cycle(self) -> None:
        """Test case for get_recovery_for_cycle

        """
        pass


if __name__ == '__main__':
    unittest.main()
