# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from whoop_client.models.cycle_score import CycleScore

class TestCycleScore(unittest.TestCase):
    """CycleScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CycleScore:
        """Test CycleScore
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CycleScore`
        """
        model = CycleScore()
        if include_optional:
            return CycleScore(
                strain = 5.2951527,
                kilojoule = 8288.297,
                average_heart_rate = 68,
                max_heart_rate = 141
            )
        else:
            return CycleScore(
                strain = 5.2951527,
                kilojoule = 8288.297,
                average_heart_rate = 68,
                max_heart_rate = 141,
        )
        """

    def testCycleScore(self):
        """Test CycleScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
