# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from whoop_client.models.workout_score import WorkoutScore

class TestWorkoutScore(unittest.TestCase):
    """WorkoutScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkoutScore:
        """Test WorkoutScore
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkoutScore`
        """
        model = WorkoutScore()
        if include_optional:
            return WorkoutScore(
                strain = 8.2463,
                average_heart_rate = 123,
                max_heart_rate = 146,
                kilojoule = 1569.34033203125,
                percent_recorded = 100.0,
                distance_meter = 1772.77035916,
                altitude_gain_meter = 46.64384460449,
                altitude_change_meter = -0.781372010707855,
                zone_duration = whoop_client.models.zone_duration.ZoneDuration(
                    zone_zero_milli = 13458, 
                    zone_one_milli = 389370, 
                    zone_two_milli = 388367, 
                    zone_three_milli = 71137, 
                    zone_four_milli = 0, 
                    zone_five_milli = 0, )
            )
        else:
            return WorkoutScore(
                strain = 8.2463,
                average_heart_rate = 123,
                max_heart_rate = 146,
                kilojoule = 1569.34033203125,
                percent_recorded = 100.0,
                zone_duration = whoop_client.models.zone_duration.ZoneDuration(
                    zone_zero_milli = 13458, 
                    zone_one_milli = 389370, 
                    zone_two_milli = 388367, 
                    zone_three_milli = 71137, 
                    zone_four_milli = 0, 
                    zone_five_milli = 0, ),
        )
        """

    def testWorkoutScore(self):
        """Test WorkoutScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
