# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictInt
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SleepNeeded(BaseModel):
    """
    Breakdown of the amount of sleep a user needed before the sleep activity. Summing all individual components results in the amount of sleep the user needed prior to this sleep activity
    """ # noqa: E501
    baseline_milli: StrictInt = Field(description="The amount of sleep a user needed based on historical trends")
    need_from_sleep_debt_milli: StrictInt = Field(description="The difference between the amount of sleep the user's body required and the amount the user actually got")
    need_from_recent_strain_milli: StrictInt = Field(description="Additional sleep need accrued based on the user's strain")
    need_from_recent_nap_milli: StrictInt = Field(description="Reduction in sleep need accrued based on the user's recent nap activity (negative value or zero)")
    __properties: ClassVar[List[str]] = ["baseline_milli", "need_from_sleep_debt_milli", "need_from_recent_strain_milli", "need_from_recent_nap_milli"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SleepNeeded from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SleepNeeded from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "baseline_milli": obj.get("baseline_milli"),
            "need_from_sleep_debt_milli": obj.get("need_from_sleep_debt_milli"),
            "need_from_recent_strain_milli": obj.get("need_from_recent_strain_milli"),
            "need_from_recent_nap_milli": obj.get("need_from_recent_nap_milli")
        })
        return _obj


