# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictInt
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SleepStageSummary(BaseModel):
    """
    Summary of the sleep stages
    """ # noqa: E501
    total_in_bed_time_milli: StrictInt = Field(description="Total time the user spent in bed, in milliseconds")
    total_awake_time_milli: StrictInt = Field(description="Total time the user spent awake, in milliseconds")
    total_no_data_time_milli: StrictInt = Field(description="Total time WHOOP did not receive data from the user during the sleep, in milliseconds")
    total_light_sleep_time_milli: StrictInt = Field(description="Total time the user spent in light sleep, in milliseconds")
    total_slow_wave_sleep_time_milli: StrictInt = Field(description="Total time the user spent in Slow Wave Sleep (SWS), in milliseconds")
    total_rem_sleep_time_milli: StrictInt = Field(description="Total time the user spent in Rapid Eye Movement (REM) sleep, in milliseconds")
    sleep_cycle_count: StrictInt = Field(description="Number of sleep cycles during the user's sleep")
    disturbance_count: StrictInt = Field(description="Number of times the user was disturbed during sleep")
    __properties: ClassVar[List[str]] = ["total_in_bed_time_milli", "total_awake_time_milli", "total_no_data_time_milli", "total_light_sleep_time_milli", "total_slow_wave_sleep_time_milli", "total_rem_sleep_time_milli", "sleep_cycle_count", "disturbance_count"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SleepStageSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SleepStageSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_in_bed_time_milli": obj.get("total_in_bed_time_milli"),
            "total_awake_time_milli": obj.get("total_awake_time_milli"),
            "total_no_data_time_milli": obj.get("total_no_data_time_milli"),
            "total_light_sleep_time_milli": obj.get("total_light_sleep_time_milli"),
            "total_slow_wave_sleep_time_milli": obj.get("total_slow_wave_sleep_time_milli"),
            "total_rem_sleep_time_milli": obj.get("total_rem_sleep_time_milli"),
            "sleep_cycle_count": obj.get("sleep_cycle_count"),
            "disturbance_count": obj.get("disturbance_count")
        })
        return _obj


