# coding: utf-8

"""
    WHOOP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ZoneDuration(BaseModel):
    """
    Breakdown of time spent in each heart rate zone during the workout.
    """ # noqa: E501
    zone_zero_milli: Optional[StrictInt] = Field(default=None, description="Time spent with Heart Rate lower than Zone One [0-50%)")
    zone_one_milli: Optional[StrictInt] = Field(default=None, description="Time spent in Heart Rate Zone One [50-60%)")
    zone_two_milli: Optional[StrictInt] = Field(default=None, description="Time spent in Heart Rate Zone Two [60-70%)")
    zone_three_milli: Optional[StrictInt] = Field(default=None, description="Time spent in Heart Rate Zone Three [70-80%)")
    zone_four_milli: Optional[StrictInt] = Field(default=None, description="Time spent in Heart Rate Zone Four [80-90%)")
    zone_five_milli: Optional[StrictInt] = Field(default=None, description="Time spent in Heart Rate Zone Five [90-100%)")
    __properties: ClassVar[List[str]] = ["zone_zero_milli", "zone_one_milli", "zone_two_milli", "zone_three_milli", "zone_four_milli", "zone_five_milli"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ZoneDuration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ZoneDuration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "zone_zero_milli": obj.get("zone_zero_milli"),
            "zone_one_milli": obj.get("zone_one_milli"),
            "zone_two_milli": obj.get("zone_two_milli"),
            "zone_three_milli": obj.get("zone_three_milli"),
            "zone_four_milli": obj.get("zone_four_milli"),
            "zone_five_milli": obj.get("zone_five_milli")
        })
        return _obj


